// GENERATED by scripts/ideal-photos/fit.mts — do not edit by hand.
// Reference photos (AI-generated, see scripts/ideal-photos/README.md) and where the ideal figure sits on
// each: photo px = ideal px × scale + (dx, dy). Uniform scale + shift keeps every angle and proportion.
import type { CaptureShot } from './capture-shots';

export interface IdealPhoto { src: string; width: number; height: number; scale: number; dx: number; dy: number }

export const IDEAL_PHOTOS: Record<CaptureShot, IdealPhoto> = {
  front: { src: '/ideal/front.jpg', width: 640, height: 1147, scale: 0.49147, dx: 73.45, dy: 60.16 },
  right: { src: '/ideal/right.jpg', width: 640, height: 1147, scale: 0.50717, dx: 66.7, dy: 48.21 },
  back: { src: '/ideal/back.jpg', width: 640, height: 1147, scale: 0.48683, dx: 76.66, dy: 74.47 },
  left: { src: '/ideal/left.jpg', width: 640, height: 1147, scale: 0.50717, dx: 66.13, dy: 48.21 },
  shoulderExtLeft: { src: '/ideal/shoulderExtLeft.jpg', width: 640, height: 1147, scale: 0.50773, dx: 55.96, dy: 46.73 },
  shoulderExtRight: { src: '/ideal/shoulderExtRight.jpg', width: 640, height: 1147, scale: 0.50773, dx: 76.31, dy: 46.73 },
  forwardFold: { src: '/ideal/forwardFold.jpg', width: 640, height: 1147, scale: 0.58995, dx: 6.88, dy: -122.28 },
  butterfly: { src: '/ideal/butterfly.jpg', width: 640, height: 794, scale: 0.56078, dx: 37.16, dy: 98.1 },
};
