// Fits each ideal figure onto its reference photo: one uniform scale + shift (no rotation, no stretch,
// so every angle and proportion — and therefore every measure and score — is unchanged), chosen by least
// squares over the body's anchor points the detector saw clearly. Writes src/lib/ideal-photos.ts.
//   npx tsx --tsconfig tsconfig.json scripts/ideal-photos/fit.mts
import { readFileSync, writeFileSync } from 'node:fs';
import { LM, type Landmark } from '../../src/lib/posture';
import { IDEAL_SHOTS, idealLandmarks, idealSize } from '../../src/lib/ideal-figures';
import type { CaptureShot } from '../../src/lib/capture-shots';

const detected: Record<string, { width: number; height: number; landmarks: Landmark[] }> =
  JSON.parse(readFileSync(new URL('./landmarks.json', import.meta.url), 'utf8'));

// Side views: the ideal figure uses the LEFT_* points as "the near side"; in the photo the near side is
// whichever of each left/right pair the detector saw better.
const SIDE: [number, number][] = [
  [LM.LEFT_EAR, LM.RIGHT_EAR], [LM.LEFT_SHOULDER, LM.RIGHT_SHOULDER], [LM.LEFT_HIP, LM.RIGHT_HIP],
  [LM.LEFT_KNEE, LM.RIGHT_KNEE], [LM.LEFT_ANKLE, LM.RIGHT_ANKLE],
];
const FOLD: [number, number][] = [[LM.LEFT_HIP, LM.RIGHT_HIP], [LM.LEFT_ANKLE, LM.RIGHT_ANKLE], [LM.LEFT_HEEL, LM.RIGHT_HEEL]];
const FRONT = [LM.NOSE, LM.LEFT_SHOULDER, LM.RIGHT_SHOULDER, LM.LEFT_HIP, LM.RIGHT_HIP, LM.LEFT_KNEE, LM.RIGHT_KNEE, LM.LEFT_ANKLE, LM.RIGHT_ANKLE];
const BUTTERFLY = [LM.NOSE, LM.LEFT_SHOULDER, LM.RIGHT_SHOULDER, LM.LEFT_HIP, LM.RIGHT_HIP];
// Fit on the trunk and legs only: arms (and the butterfly's knees) are the part the photo may not match.
// Each anchor: [ideal landmark index, candidate photo landmark indices (best-seen one is used)].
const pairsOf = (list: [number, number][]) => list.map(([l, r]) => [l, [l, r]] as [number, number[]]);
const same = (list: number[]) => list.map((i) => [i, [i]] as [number, number[]]);
const ANCHORS: Record<CaptureShot, [number, number[]][]> = {
  front: same(FRONT), back: same(FRONT), butterfly: same(BUTTERFLY),
  right: pairsOf(SIDE), left: pairsOf(SIDE), shoulderExtRight: pairsOf(SIDE), shoulderExtLeft: pairsOf(SIDE),
  forwardFold: pairsOf(FOLD),
};
const MIN_VIS = 0.3;

const out: Record<string, { width: number; height: number; scale: number; dx: number; dy: number }> = {};
for (const shot of IDEAL_SHOTS) {
  const photo = detected[shot];
  const ideal = idealLandmarks(shot), size = idealSize(shot);
  const pairs = ANCHORS[shot].flatMap(([idealIdx, photoIdx]) => {
    const q = photoIdx.map((k) => photo.landmarks[k]).sort((a, b) => b.visibility - a.visibility)[0];
    const p = ideal[idealIdx];
    if (!p.visibility || q.visibility < MIN_VIS) return [];
    return [{ p: { x: p.x * size.width, y: p.y * size.height }, q: { x: q.x * photo.width, y: q.y * photo.height } }];
  });
  if (pairs.length < 3) throw new Error(`${shot}: only ${pairs.length} anchor points detected`);
  const mean = (xs: number[]) => xs.reduce((a, b) => a + b, 0) / xs.length;
  const px = mean(pairs.map((v) => v.p.x)), py = mean(pairs.map((v) => v.p.y));
  const qx = mean(pairs.map((v) => v.q.x)), qy = mean(pairs.map((v) => v.q.y));
  const num = pairs.reduce((s, v) => s + (v.p.x - px) * (v.q.x - qx) + (v.p.y - py) * (v.q.y - qy), 0);
  const den = pairs.reduce((s, v) => s + (v.p.x - px) ** 2 + (v.p.y - py) ** 2, 0);
  const scale = num / den;
  out[shot] = { width: photo.width, height: photo.height, scale: +scale.toFixed(5), dx: +(qx - scale * px).toFixed(2), dy: +(qy - scale * py).toFixed(2) };
  console.log(shot.padEnd(17), `${pairs.length} anchors`, out[shot]);
}

writeFileSync(new URL('../../src/lib/ideal-photos.ts', import.meta.url), `// GENERATED by scripts/ideal-photos/fit.mts — do not edit by hand.
// Reference photos (AI-generated, see scripts/ideal-photos/README.md) and where the ideal figure sits on
// each: photo px = ideal px × scale + (dx, dy). Uniform scale + shift keeps every angle and proportion.
import type { CaptureShot } from './capture-shots';

export interface IdealPhoto { src: string; width: number; height: number; scale: number; dx: number; dy: number }

export const IDEAL_PHOTOS: Record<CaptureShot, IdealPhoto> = {
${Object.entries(out).map(([k, v]) => `  ${k}: { src: '/ideal/${k}.jpg', width: ${v.width}, height: ${v.height}, scale: ${v.scale}, dx: ${v.dx}, dy: ${v.dy} },`).join('\n')}
};
`);
